### PR TITLE
Hehe

### PR DESCRIPTION
**Pull request by desharish**
idk what write here

### CODE REVIEW

**Comment by Lncvrt** [comment]
I don't understand what the point of a Russian Fork would be needed for, just modify the config of posiedon.

**Comment by Lncvrt** [comment]
So far it just seems like you are trying to reown posiedon and call it vodka

**Comment by Lncvrt** [comment]
> it's a troll PR

I meant the repo.

**Comment by Lncvrt** [comment]
seems he scrapped it. this was a real project but I think he realized the github.com website isn't the greatest IDE especially for no knowledge.

**Comment by CfggC00l** [comment]
Yes it was a real project I GOT AN ARCHIVE OF THE PROJECT VODKA JAR. Dude was trying to make this a real thing lmao.

https://web.archive.org/web/20240803191940/https://github.com/desharish/Project-Vodka/releases/download/Maven/proj-vodko-0.0.1.jar

**Comment by Lncvrt** [comment]
Trying. This was literally an attempt to reown Posiedon lmao

**Pull request closed without merging**
