### PR TITLE
Hacking kick changes

### PR DESCRIPTION
**Pull request by Strultz**
Add hacking kick for invalid item slots
remove "Moved too quickly (hacking?)" kick and replace it with a teleport

### CODE REVIEW

**Comment by moderatorman** [comment]
I like this, but I would suggest adding an option in the configuration for it, as some might prefer the vanilla behavior.

**Comment by Strultz** [comment]
ok, added

**Comment by moderatorman** [comment]
Now to wait for Muffin Man to merge, I suppose.

**Comment by RhysB** [comment]
Looks good

**Pull request merged**
