### PR TITLE
Commands can be hidden from being logged in console now

### PR DESCRIPTION
**Pull request by MrMasrozYTLIVE**
Well the name should describe everything

### CODE REVIEW

**Comment by CodeKid0** [comment]
Is it tested?

**Comment by MrMasrozYTLIVE** [comment]
image
Tested it on uberbukkit with my own auth plugin. It works. Can test it again but on b1.7.3

**Comment by MrMasrozYTLIVE** [comment]
image
image

**Comment by RhysB** [comment]
Apologies for the late reply.

This is a really good change. I only have one requested change, however. 

Is it possible to keep the old hardcoded commands blocked? Just throwing this out there because most servers still use 2011-era auth plugins like AuthMe or XAuth. These plugins, as we know, don't have this feature and server owners probably won't rush to patch these plugins.

I get that it might take away a bit from the new feature, but I really think it's important that we keep player passwords from being logged and stored in plain text. It's a pretty big security issue.

**Comment by MrMasrozYTLIVE** [comment]
> Is it possible to keep the old hardcoded commands blocked?

They are locked though.
image

**Comment by RhysB** [comment]
Ahh, apologies for my mistake. Commit looks good to me.

Thanks for contributing :)

**Pull request merged**
